name: check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.44.4"
          channel: "stable"
          cache: true
      - run: ./meta.sh check
